" also look at https://vimawesome.com/
filetype plugin indent on
syntax on

set number
set encoding=utf-8
set noautoindent " not too sure but otherwise pasting is messed up
set ruler
set t_BE= " fix weird pasting in unix
set t_Co=16
set path+=** " path relative to current working dir
set hls " hilight searches
set is  " incremental search
set ic  " ignore case
set splitright " splits open to the left
set splitbelow " splits open below, not above current split
set cursorline
hi CursorLine   cterm=NONE ctermbg=7

" Tabs to 4 spaces
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" autocomplete vim commands
set wildmenu
set wildmode=longest:list,full
set autoread " automatically refreshing tabs
au FocusGained,BufEnter * :checktime " for autoread to work

"Remap split navigations to movement keys
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

"Netrw parameters
let g:netrw_banner = 0       " do not show header
let g:netrw_liststyle = 3    " Display in a tree
let g:netrw_browse_split = 4 " Open in previous window
let g:netrw_altv = 1         " Open files to the right
let g:netrw_winsize = 15

let g:airline_powerline_fonts = 1
let g:airline_theme="solarized"
" let g:airline_solarized_bg='dark'

" syntax for plsql and dpyml
autocmd BufRead,BufNewFile *.dpyml set syntax=dpyml
autocmd BufRead,BufNewFile *.sql set syntax=plsql

" CTRL-L to toggle line numbers
function! g:ToggleNuMode()
  if &rnu == 1
   set nornu
     else
  set rnu
    endif
endfunction
" map toggling line numbers to <F4>
nnoremap <silent><F4> :call g:ToggleNuMode()<cr>

" Signify plugin
let g:signify_vcs_list = [ 'git', 'svn' ] " limit to git and svn
" let g:signify_realtime = 0  " realtime updateing
let g:signify_sign_delete = '-'
let g:signify_sign_change = '~'

highlight DiffAdd           cterm=bold ctermbg=none ctermfg=28
highlight DiffDelete        cterm=bold ctermbg=none ctermfg=167
highlight DiffChange        cterm=bold ctermbg=none ctermfg=172

" YouCompleteMe params
let g:ycm_python_binary_path = '/usr/bin/python3'

